; Listing generated by Microsoft (R) Optimizing Compiler Version 14.00.50727.762 

	TITLE	d:\2016-05-25f-win-osdev14-Demo6_1\osdev14-Demo6\SysCore\Kernel\entry.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?kernel_entry@@YAXXZ				; kernel_entry
EXTRN	?Exit@@YAXXZ:PROC				; Exit
EXTRN	_main:PROC
EXTRN	?InitializeConstructors@@YAXXZ:PROC		; InitializeConstructors
; Function compile flags: /Ogtp
; File d:\2016-05-25f-win-osdev14-demo6_1\osdev14-demo6\syscore\kernel\entry.cpp
;	COMDAT ?kernel_entry@@YAXXZ
_TEXT	SEGMENT
?kernel_entry@@YAXXZ PROC				; kernel_entry, COMDAT

; 13   : void _cdecl kernel_entry () {

	push	ebx

; 14   : 
; 15   : #ifdef ARCH_X86
; 16   : 	_asm {
; 17   : 		cli						// clear interrupts--Do not enable them yet

	cli

; 18   : 		xchg bx,bx

	xchg	bx, bx

; 19   : 		xchg bx,bx

	xchg	bx, bx

; 20   : 		xchg bx,bx

	xchg	bx, bx

; 21   : 		xchg bx,bx

	xchg	bx, bx

; 22   : 		xchg bx,bx

	xchg	bx, bx

; 23   : 		xchg bx,bx

	xchg	bx, bx

; 24   : 		mov ax, 10h				// offset 0x10 in gdt for data selector, remember?

	mov	ax, 16					; 00000010H

; 25   : 		mov ds, ax

	mov	ds, ax

; 26   : 		mov es, ax

	mov	es, ax

; 27   : 		mov fs, ax

	mov	fs, ax

; 28   : 		mov gs, ax

	mov	gs, ax

; 29   : 		mov ss, ax				// Set up base stack

	mov	ss, ax

; 30   : 		mov esp, 0x90000

	mov	esp, 589824				; 00090000H

; 31   : 		mov ebp, esp			// store current stack pointer

	mov	ebp, esp

; 32   : 		push ebp

	push	ebp

; 33   : 	}
; 34   : #endif
; 35   : 
; 36   : 	//! Execute global constructors
; 37   : 	InitializeConstructors();

	call	?InitializeConstructors@@YAXXZ		; InitializeConstructors

; 38   : 
; 39   : 	//!	Call kernel entry point
; 40   : 	main ();

	call	_main

; 41   : 
; 42   : 	//! Cleanup all dynamic dtors
; 43   : 	Exit ();

	call	?Exit@@YAXXZ				; Exit

; 44   : 
; 45   : #ifdef ARCH_X86
; 46   : 	_asm cli

	cli
	npad	1
$LL2@kernel_ent:

; 47   : #endif
; 48   : 	for (;;);

	jmp	SHORT $LL2@kernel_ent
?kernel_entry@@YAXXZ ENDP				; kernel_entry
_TEXT	ENDS
END
